/**
 * Created by InspireUI on 17/02/2017.
 *
 * @format
 */

const Images = {
  options: require('@images/options.png'),
  back: require('@images/back.png'),
  downarrow: require('@images/downarrow.png'),
  logo: require('@images/logo.png'),
  menu: require('@images/menu.png'),
  plus: require('@images/plus.png'),
  reset: require('@images/reset.png'),
  sale: require('@images/sale.png'),
  items: require('@images/items.png'),
  invoice: require('@images/invoice.png'),
  credit: require('@images/credit.png'),
  estimate: require('@images/estimate.png'),
  customer: require('@images/customer.png'),

  filter: require('@images/filter.png'),
  file: require('@images/file.png'),
  print: require('@images/print.png'),

  plusblue: require('@images/plusblue.png'),
  backred: require('@images/backred.png'),
  edit: require('@images/penedit.png'),
  bin: require('@images/bin.png'),
  uparrow: require('@images/up-arrow.png'),
  downarow: require('@images/down-arrow.png'),
  float: require('@images/float.png'),
  copy: require('@images/copy.png'),
  forgot: require('@images/forgot.png'),
  correct: require('@images/correct.png'),
  paytm: require('@images/paytm.png'),
  wrong: require('@images/wrong.png'),
  arrows: require('@images/arrows.png'),
  interface: require('@images/interface.png'),
  more: require('@images/more.png'),
  search: require('@images/search.png'),
  pencil: require('@images/pencil.png'),
  mail: require('@images/mail.png'),
  lock: require('@images/lock.png'),
  bglogin: require('@images/bglogin.gif'),
  bglogin2: require('@images/bglogin2.gif'),
  next: require('@images/next.png'),
  meter: require('@images/meter.png'),
  transport: require('@images/transport.png'),
  care: require('@images/care.png'),
  create: require('@images/create.png'),
  line: require('@images/line.png'),
  user: require('@images/user.png'),
  role: require('@images/role.png'),
  add: require('@images/add.png'),
  expand: require('@images/expand.png'),
  backwhite: require('@images/backwhite.png'),
  filterw : require('@images/filterw.png'),
  alert : require('@images/alert.png'),
  block : require('@images/block.png'),
  eye: require('@images/eye.png'),
  excel: require('@images/excel.png'),
  close:require('@images/close.png'),
  logout: require('@images/logout.png'),
  trash: require('@images/trash.png'),
  printer: require('@images/printer.png'),
  eyeclose: require('@images/eyeclose.png'),
  loginbg: require('@images/loginbg.png'),
  listbg: require('@images/listbg.png'),
};

export default Images;
